author: TechTastic
book_id: "hexmapping:thehexbook"
default_branch: main
github_repo: hexmapping
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexMappingModPlugin
hexdoc_plugin_classname: HexMappingPlugin
java_lang:
  ext: java
  src: java
java_package: io/github/techtastic/hexmapping
mod_display_name: HexMapping
modid: hexmapping
multiloader: true
pages_url: https://techtastic.github.io/hexmapping
pattern_regex:
  regex: '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?'
  per_world_value: registerPerWorld
pattern_registry: registry/HexMappingPatternRegistry.java
